/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    CreditCardApplications: {
      address: "0x610178dA211FEF7D417bC0e6FeD39F05609AD788",
      abi: [
        {
          anonymous: false,
          inputs: [],
          name: "AllApplicationsReset",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "applicant",
              type: "address",
            },
          ],
          name: "ApplicationApproved",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "applicant",
              type: "address",
            },
          ],
          name: "ApplicationRejected",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "applicant",
              type: "address",
            },
          ],
          name: "ApplicationSubmitted",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "applicant",
              type: "address",
            },
          ],
          name: "approve",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "getAllApplicants",
          outputs: [
            {
              internalType: "address[]",
              name: "",
              type: "address[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "index",
              type: "uint256",
            },
          ],
          name: "getApplicantAt",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getApplicantCount",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "applicant",
              type: "address",
            },
          ],
          name: "getApplication",
          outputs: [
            {
              components: [
                {
                  internalType: "address",
                  name: "applicant",
                  type: "address",
                },
                {
                  internalType: "enum CreditCardApplications.ApplicationStatus",
                  name: "status",
                  type: "uint8",
                },
                {
                  internalType: "uint256",
                  name: "createdAt",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "decidedAt",
                  type: "uint256",
                },
              ],
              internalType: "struct CreditCardApplications.Application",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getMyApplication",
          outputs: [
            {
              components: [
                {
                  internalType: "address",
                  name: "applicant",
                  type: "address",
                },
                {
                  internalType: "enum CreditCardApplications.ApplicationStatus",
                  name: "status",
                  type: "uint8",
                },
                {
                  internalType: "uint256",
                  name: "createdAt",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "decidedAt",
                  type: "uint256",
                },
              ],
              internalType: "struct CreditCardApplications.Application",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "applicant",
              type: "address",
            },
          ],
          name: "reject",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "resetAll",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "submitApplication",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 38,
    },
    CreditPassport: {
      address: "0x0165878A594ca255338adfa4d48449f69242Eb8F",
      abi: [
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "index",
              type: "uint256",
            },
          ],
          name: "ProfileAdded",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "previousCount",
              type: "uint256",
            },
          ],
          name: "ProfilesCleared",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "country",
              type: "string",
            },
            {
              internalType: "string",
              name: "name",
              type: "string",
            },
            {
              internalType: "string",
              name: "score",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "ageMonths",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "cards",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "totalAccounts",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "utilization",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "delinquencies",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "ipfsCid",
              type: "string",
            },
          ],
          name: "addProfile",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "deleteMyProfiles",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "getMyProfiles",
          outputs: [
            {
              components: [
                {
                  internalType: "string",
                  name: "country",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "name",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "score",
                  type: "string",
                },
                {
                  internalType: "uint256",
                  name: "ageMonths",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "cards",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "totalAccounts",
                  type: "uint256",
                },
                {
                  internalType: "string",
                  name: "utilization",
                  type: "string",
                },
                {
                  internalType: "uint256",
                  name: "delinquencies",
                  type: "uint256",
                },
                {
                  internalType: "string",
                  name: "ipfsCid",
                  type: "string",
                },
                {
                  internalType: "uint256",
                  name: "timestamp",
                  type: "uint256",
                },
              ],
              internalType: "struct CreditPassport.CreditProfile[]",
              name: "",
              type: "tuple[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "index",
              type: "uint256",
            },
          ],
          name: "getProfile",
          outputs: [
            {
              internalType: "string",
              name: "country",
              type: "string",
            },
            {
              internalType: "string",
              name: "name",
              type: "string",
            },
            {
              internalType: "string",
              name: "score",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "ageMonths",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "cards",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "totalAccounts",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "utilization",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "delinquencies",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "ipfsCid",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "timestamp",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "user",
              type: "address",
            },
          ],
          name: "getProfileCount",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "user",
              type: "address",
            },
          ],
          name: "getProfiles",
          outputs: [
            {
              components: [
                {
                  internalType: "string",
                  name: "country",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "name",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "score",
                  type: "string",
                },
                {
                  internalType: "uint256",
                  name: "ageMonths",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "cards",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "totalAccounts",
                  type: "uint256",
                },
                {
                  internalType: "string",
                  name: "utilization",
                  type: "string",
                },
                {
                  internalType: "uint256",
                  name: "delinquencies",
                  type: "uint256",
                },
                {
                  internalType: "string",
                  name: "ipfsCid",
                  type: "string",
                },
                {
                  internalType: "uint256",
                  name: "timestamp",
                  type: "uint256",
                },
              ],
              internalType: "struct CreditPassport.CreditProfile[]",
              name: "",
              type: "tuple[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 24,
    },
    YourContract: {
      address: "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "_owner",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "greetingSetter",
              type: "address",
            },
            {
              indexed: false,
              internalType: "string",
              name: "newGreeting",
              type: "string",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "premium",
              type: "bool",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "GreetingChange",
          type: "event",
        },
        {
          inputs: [],
          name: "greeting",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "premium",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "_newGreeting",
              type: "string",
            },
          ],
          name: "setGreeting",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [],
          name: "totalCounter",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "userGreetingCounter",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "withdraw",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          stateMutability: "payable",
          type: "receive",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 10,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
